Repository MangKlutz/MangKlutz.github.io, pull requests merged in 2024-07, with the labels that each got.

#17 registration page initial
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.css
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.min.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.rtl.css
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.rtl.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.rtl.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap-grid.rtl.min.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.css
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.min.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.rtl.css
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.rtl.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.rtl.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap-reboot.rtl.min.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.css
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.min.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.rtl.css
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.rtl.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.rtl.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap-utilities.rtl.min.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap.css
  project/bootstrap-5.3.3-dist/css/bootstrap.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap.min.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap.rtl.css
  project/bootstrap-5.3.3-dist/css/bootstrap.rtl.css.map
  project/bootstrap-5.3.3-dist/css/bootstrap.rtl.min.css
  project/bootstrap-5.3.3-dist/css/bootstrap.rtl.min.css.map
  project/bootstrap-5.3.3-dist/js/bootstrap.bundle.js
  project/bootstrap-5.3.3-dist/js/bootstrap.bundle.js.map
  project/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js
  project/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js.map
  project/bootstrap-5.3.3-dist/js/bootstrap.esm.js
  project/bootstrap-5.3.3-dist/js/bootstrap.esm.js.map
  project/bootstrap-5.3.3-dist/js/bootstrap.esm.min.js
  project/bootstrap-5.3.3-dist/js/bootstrap.esm.min.js.map
  project/bootstrap-5.3.3-dist/js/bootstrap.js
  project/bootstrap-5.3.3-dist/js/bootstrap.js.map
  project/bootstrap-5.3.3-dist/js/bootstrap.min.js
  project/bootstrap-5.3.3-dist/js/bootstrap.min.js.map
  project/images/facebook.png
  project/images/google.png
  project/images/nintendo.png
  project/registration.css
  project/registration.html
  project/registration.js
Labels: documentation

#20 login
  .vscode/settings.json
  project/Login.css
  project/login.html
Labels: question

#21 FINAL VERSION REGISTRATION
  project/images/pkbg.jpg
  project/registration.css
  project/registration.html
Labels: FINISHED

#22 REGISTRATION PAGE FINAL VERSION 2
  project/registration.css
Labels: bug, enhancement, FINISHED

#27 eto na talaga yung final
  project/index.html
  sa1Evangelista/index.css
  sa1Evangelista/index.html
  sa1Evangelista/index.js
Labels: FINISHED

#30 pinaka-finale
  project/product.html
Labels: documentation, FINISHED

#32 about
  about-page/about.css
  about-page/about.html
  about-page/about.js
Labels: documentation, enhancement, help wanted

#33 Update login.html
  project/login.html
Labels: enhancement, FINISHED

#34 final - about page
  about-page/about.css
  about-page/about.html
  about-page/about.js
  project/about.css
  project/about.html
  project/about.js
  project/images/about_bg.jpg
  project/images/angelica.jpg
  project/images/bri.jpg
  project/images/john.jpg
  project/images/juliana.jpg
  project/images/sandra.jpg
Labels: FINISHED
